apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: eureka
  namespace: test
spec:
  interval: 1m
  chart: ./eureka
  sourceRef:
    kind: GitRepository
    name: test
  version: 0.1.0
  valuesFiles:
    - eureka/values.yaml