apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: microservice-release
  namespace: test
spec:
  interval: 1m
  chartRef:
    kind: HelmChart
    name: pfe-microservice
    namespace: test